#!/usr/bin/env python3
"""
Pydantic Schemas for Claude Code Hooks
Generated by claude-hook-pydantic-validator
"""

from pydantic import BaseModel, Field, validator, model_validator
from typing import Optional, Dict, Any, List, Literal
from datetime import datetime


class ToolInput(BaseModel):
    """Tool-specific input parameters."""
    file_path: Optional[str] = None
    command: Optional[str] = None
    url: Optional[str] = None
    pattern: Optional[str] = None
    content: Optional[str] = None
    old_string: Optional[str] = None
    new_string: Optional[str] = None
    prompt: Optional[str] = None
    description: Optional[str] = None

    @validator('file_path')
    def validate_file_path(cls, v):
        """Validate file path for security issues."""
        if v and '..' in v:
            raise ValueError("Path traversal detected in file_path")
        return v

    class Config:
        extra = 'allow'  # Allow additional tool-specific fields


class HookInput(BaseModel):
    """Schema for hook stdin input."""
    session_id: str = Field(..., description="Session identifier")
    transcript_path: str = Field(..., description="Conversation JSON location")
    cwd: str = Field(..., description="Current working directory")
    permission_mode: Literal["default", "plan", "acceptEdits", "bypassPermissions"]
    hook_event_name: str
    tool_name: str = Field(..., description="Name of tool being invoked")
    tool_input: ToolInput = Field(..., description="Tool-specific parameters")
    timestamp: Optional[datetime] = None

    class Config:
        extra = 'allow'  # Allow additional fields for compatibility
        validate_assignment = True  # Validate on attribute assignment

    @validator('tool_name')
    def validate_tool_name(cls, v):
        """Validate tool name is in whitelist."""
        allowed_tools = {
            'Read', 'Write', 'Edit', 'Bash', 'WebFetch', 'WebSearch',
            'Glob', 'Grep', 'Task', 'NotebookEdit', 'Skill',
            'SlashCommand', 'AskUserQuestion', 'TodoWrite'
        }
        if v not in allowed_tools:
            raise ValueError(
                f"Unknown tool: {v}. "
                f"Allowed tools: {', '.join(sorted(allowed_tools))}"
            )
        return v

    @validator('cwd')
    def validate_cwd(cls, v):
        """Validate current working directory."""
        if not v or not isinstance(v, str):
            raise ValueError("cwd must be non-empty string")
        return v


class HookDecision(BaseModel):
    """Schema for hook decision output."""
    decision: Literal["ALLOWED", "BLOCKED", "RETRY"]
    reason: Optional[str] = None
    details: Dict[str, Any] = {}
    continue_execution: bool = True
    updated_input: Optional[Dict[str, Any]] = None
    additional_context: Optional[str] = None

    class Config:
        validate_assignment = True

    def to_stderr(self) -> str:
        """Format for stderr output."""
        return self.model_dump_json()

    def to_stdout(self) -> str:
        """Format for stdout output."""
        return self.model_dump_json()


class SecurityConfig(BaseModel):
    """Schema for security-config.json."""
    version: str
    fail_closed: bool = True
    restricted_paths: List[str]
    allowed_paths: List[str]
    dangerous_bash_patterns: List[str]
    allowed_domains: Optional[List[str]] = []
    rate_limits: Dict[str, int]
    monitoring: Optional[Dict[str, Any]] = {}

    @validator('rate_limits')
    def validate_rate_limits(cls, v):
        """Validate rate limits are positive integers."""
        for tool, limit in v.items():
            if not isinstance(limit, int):
                raise ValueError(
                    f"Rate limit for {tool} must be integer, got {type(limit).__name__}"
                )
            if limit < 0:
                raise ValueError(
                    f"Rate limit for {tool} must be positive, got {limit}"
                )
        return v

    @validator('restricted_paths', 'allowed_paths')
    def validate_paths(cls, v):
        """Validate paths are non-empty strings."""
        if not v:
            raise ValueError("Path list cannot be empty")
        for path in v:
            if not isinstance(path, str) or not path.strip():
                raise ValueError(f"Invalid path: {path}")
        return v


class StorageRule(BaseModel):
    """Single storage rule."""
    priority: str
    authorized: Dict[str, Any]
    denied: Dict[str, Any]
    android_executable_exception: Optional[Dict[str, Any]] = None


class StorageRules(BaseModel):
    """Schema for storage-rules.json."""
    version: str
    enforced: bool
    rules: Dict[str, StorageRule]

    class Config:
        extra = 'allow'


class AuditLogEntry(BaseModel):
    """Schema for audit log entries."""
    timestamp: datetime = Field(default_factory=datetime.now)
    tool: str
    decision: Literal["ALLOWED", "BLOCKED", "RETRY"]
    reason: Optional[str] = None
    file_path: Optional[str] = None
    command: Optional[str] = None
    session_id: str
    validation_info: Optional[Dict[str, Any]] = None

    def to_jsonl(self) -> str:
        """Export as JSONL for audit.jsonl."""
        return self.model_dump_json()


# Convenience functions for common operations

def validate_hook_input_dict(data: Dict) -> tuple[bool, List[str]]:
    """
    Validate hook input dictionary.

    Args:
        data: Raw dictionary from JSON

    Returns:
        (True, []) if valid
        (False, [error_messages]) if invalid
    """
    try:
        HookInput(**data)
        return True, []
    except Exception as e:
        from pydantic import ValidationError
        if isinstance(e, ValidationError):
            errors = [
                f"{'.'.join(map(str, err['loc']))}: {err['msg']}"
                for err in e.errors()
            ]
            return False, errors
        else:
            return False, [str(e)]


def validate_security_config_dict(data: Dict) -> tuple[bool, List[str]]:
    """
    Validate security config dictionary.

    Args:
        data: Raw dictionary from JSON

    Returns:
        (True, []) if valid
        (False, [error_messages]) if invalid
    """
    try:
        SecurityConfig(**data)
        return True, []
    except Exception as e:
        from pydantic import ValidationError
        if isinstance(e, ValidationError):
            errors = [
                f"{'.'.join(map(str, err['loc']))}: {err['msg']}"
                for err in e.errors()
            ]
            return False, errors
        else:
            return False, [str(e)]
